### ISSUE TITLE
where I can find the dataset build program ?

### ISSUE THREAD

**Issue by lixusign** [BUPT-GAMMA/OpenHGNN#10]
for ex : https://github.com/BUPT-GAMMA/OpenHGNN/tree/main/openhgnn/dataset#academic4HetGNN 
in this dataset

when I  extract_archive , A bin file about g。

but where I can find ， how to build this dataset use dgl standalone program ?

**Comment by Theheavens** [comment]
Maybe you can refer to https://github.com/BUPT-GAMMA/OpenHGNN/tree/main/openhgnn/dataset#how-to-build-a-new-dataset

**Comment by lixusign** [comment]
thxreply, but I mean ,  where I can find academic4HetGNN explain,  about feature name,  feature size, what the feature mean and so on

**Comment by Theheavens** [comment]
For now we process the dataset used in the paper, so the academic4HetGNN is from [HetGNN](https://github.com/BUPT-GAMMA/OpenHGNN/tree/main/openhgnn/output/HetGNN). But in the paper or source code, there is no more information.

**Comment by lixusign** [comment]
thx
