### ISSUE TITLE
No trainflow for ie-HGCN?

### ISSUE THREAD

**Issue by buaalyx** [BUPT-GAMMA/OpenHGNN#127]
## ❓ Questions and Help
It seems there is no specific trainflow for the new-added trainflow ie-HGCN in openhgnn/experiment.py, then how can I run this model?
Thanks for the reply.

**Comment by dddg617** [comment]
Thanks for the question. The answer is yes, we do not design a specific trainerflow for ie-HGCN. The experiment of this model is object classification, which is node classification, so we just use the node classification trainerflow.
