### ISSUE TITLE
关于SimpleHGN结果复现问题

### ISSUE THREAD

**Issue by GorgeousMe** [BUPT-GAMMA/OpenHGNN#140]
该框架好像并不能复现出HGB论文的实验结果

**Comment by dddg617** [comment]
Many factors will affect the outcome such as the hyper parameters and the random seeds. So, we can only fit the results as closely as possible but it is difficult to achieve perfect consistency. As far as I know, the implement of the source code is different from our implementation, so this may also affect the outcome.
