### ISSUE TITLE
How to train model using own dataset？

### ISSUE THREAD

**Issue by Fino2020** [BUPT-GAMMA/OpenHGNN#141]
## ❓ Questions and Help
I want to train my own HNN data, could you tell me how to edit this code? the data in `./openhgnn/dataset` are download from `https://s3.cn-north-1.amazonaws.com.cn/dgl-data/` and is `.bin` file. So how could I change this dataset?
救救孩子

**Comment by Zhanghyi** [comment]
You can refer to https://github.com/BUPT-GAMMA/OpenHGNN/tree/main/examples/customization
