### ISSUE TITLE
run HGSL model error

### ISSUE THREAD

**Issue by vchopin** [BUPT-GAMMA/OpenHGNN#143]
## 🐛 Bug

when i run the suggest command : 
```python
python main.py -m HGSL -d acm4GTN -t node_classification -g 0 --use_best_config
```
this raise an error like:

Traceback (most recent call last):
  File "main.py", line 21, in <module>
    experiment.run()
  File "/workspace/OpenHGNN/openhgnn/experiment.py", line 97, in run
    flow = build_flow(self.config, trainerflow)
  File "/workspace/OpenHGNN/openhgnn/trainerflow/__init__.py", line 46, in build_flow
    return FLOW_REGISTRY[flow_name](args)
  File "/workspace/OpenHGNN/openhgnn/trainerflow/node_classification.py", line 42, in __init__
    self.model = build_model(self.model).build_model_from_args(self.args, self.hg).to(self.device)
  File "/workspace/OpenHGNN/openhgnn/models/HGSL.py", line 106, in build_model_from_args
    mp_emb_dim = hg.nodes["paper"].data["pap_m2v_emb"].shape[1]
  File "/opt/conda/lib/python3.7/site-packages/dgl/view.py", line 73, in __getitem__
    return self._graph._get_n_repr(self._ntid, self._nodes)[key]
  File "/opt/conda/lib/python3.7/site-packages/dgl/frame.py", line 622, in __getitem__
    return self._columns[name].data
KeyError: 'pap_m2v_emb'

it seems like there is no pap_m2v_emb key in paper nodes data， so how to fix it?

-------------------------------------------------------------------
more error update:
when I just make `mp_emb_dim=0` to jump this line, more errors raise, such as no `hidden_dim`、`mini_batch_flag`  ... defined in config, besides,  when I successfully run this model, another exception was raised:

![image](https://user-images.githubusercontent.com/53134305/205070320-014cae32-c873-4536-bfbc-cee40a7f778f.png)

Do you have an updated version of the model？

Sincere thanks.

## To Reproduce

1.cd OpenHGNN
2.python main.py -m HGSL -d acm4GTN -t node_classification -g 0 --use_best_config

## Environment

 - OpenHGNN Version (e.g., 1.0):
 - PyTorch latest, DGL latest
 -  Linux
 - python main.py -m HGSL -d acm4GTN -t node_classification -g 0 --use_best_config
 - best_config for recommend

**Comment by lazishu2000** [comment]
Sorry, it seems that a bug occurred during dataset migration. It is fixed right now, please pull the new version if you want to run this model. Besides, you can not only use --use_bese_config, but also change HGSL's config in openhgnn/config.ini now.
Sorry for any trouble we caused you.
