### ISSUE TITLE
This demo is no longer valid

### ISSUE THREAD

**Issue by xbinglzh** [BUPT-GAMMA/OpenHGNN#163]
## ❓ Questions and Help

How to build a new dataset
Overview

We use [dgl.heterograph](https://docs.dgl.ai/en/latest/guide/graph-heterogeneous.html#guide-graph-heterogeneous) as our graph data structure.

The API [dgl.save_graphs](https://docs.dgl.ai/en/latest/generated/dgl.save_graphs.html) and [dgl.load_graphs](https://docs.dgl.ai/en/latest/generated/dgl.load_graphs.html#) can be used in storing graph into the local.
The Flow

    Process your dataset as [dgl.heterograph](https://docs.dgl.ai/en/latest/guide/graph-heterogeneous.html#guide-graph-heterogeneous).
    Store as graph.bin. Compress as dataset_name4model_name.zip
    Upload the zip file to s3.
    If the dataset is Heterogeneous Information Network, you can modify the [AcademicDataset](https://github.com/BUPT-GAMMA/OpenHGNN/blob/main/openhgnn/dataset/academic_graph.py) directly. Or you can refer to it building a new Class Dataset.

We give a [demo](https://openhgnn.readthedocs.io/en/latest/install/usage.html#evaluate-a-new-dataset) to build a new dataset.

[demo](https://openhgnn.readthedocs.io/en/latest/install/usage.html#evaluate-a-new-dataset)
This demo is no longer valid

**Comment by dddg617** [comment]
Thanks for the questions, we will fix this soon, the new demo link is here: https://openhgnn.readthedocs.io/en/latest/advanced_materials/developer_guide.html#evaluate-a-new-dataset.
