### ISSUE TITLE
数据集的重复处理/预处理数据集文件缓存无效

### ISSUE THREAD

**Issue by SpaceZore** [BUPT-GAMMA/OpenHGNN#170]
在dataset模块中有设定可以将数据集中的raw数据处理成框架可以接收的格式后缓存为bin文件，以备下次快速读入无需重复处理，但是有些方法因为未对has_cache方法实现，导致每次都要重新读入原始文件并处理。例如openhgnn/dataset/gtn_dataset.py，可以加一个实现`    def has_cache(self):
        return os.path.isfile(os.path.join(self.save_path, 'graph.bin'))`

**Comment by lazishu2000** [comment]
收到你的建议！感谢！
我们已经着手修复了这个问题，因为其他的数据集没有process逻辑，目前只修改了gtn_dataset。
相关提交：commit 5e5e564
如果有任何问题，期待更多联系。
