### ISSUE TITLE
Failed to import embedding flows.

### ISSUE THREAD

**Issue by Rilke123** [BUPT-GAMMA/OpenHGNN#185]
when run the task of 'embedding' with the model 'MAGNN',  it has the error 'Failed to import embedding flows.'
from openhgnn import Experiment
experiment = Experiment(model='MAGNN', dataset='acm4GTN', task='embedding', gpu=-1, lr=0.05, hidden_dim=64,
                        max_epoch=30, num_layers=3)
experiment.run()

**Comment by lazishu2000** [comment]
Thanks for your comment.
We don't support 'embedding' task for MAGNN model now.
Please try "task='node_classification/link_prediction'".

**Comment by aisilu5** [comment]
when i run "python main.py -m HGNN_AC -t node_classification -d imdb4MAGNN -g 0"
 it has the error "Failed to import node_classification_ac flows."
Basic setup of this experiment: 
     model: HGNN_AC    
     dataset: imdb4MAGNN   
     task: node_classification. 
 This experiment has following parameters. You can use set_params to edit them.
 Use print(experiment) to print this information again.

**Comment by aisilu5** [comment]
when i run "python main.py -m HGNN_AC -t node_classification -d acm4NSHE -g 0" or "python main.py -m HGNN_AC -t node_classification -d imdb4MAGNN -g 0"
it has the error  “
Traceback (most recent call last):
  File "/home/bfs/CE/OpenHGNN/main.py", line 21, in <module>
    experiment.run()
  File "/home/bfs/CE/OpenHGNN/openhgnn/experiment.py", line 120, in run
    result = flow.train()
  File "/home/bfs/CE/OpenHGNN/openhgnn/trainerflow/node_classification_ac.py", line 119, in train
    self.preprocess()
  File "/home/bfs/CE/OpenHGNN/openhgnn/trainerflow/node_classification_ac.py", line 114, in preprocess
    self.preprocess_feature()
AttributeError: 'NodeClassificationAC' object has no attribute 'preprocess_feature'”
