### ISSUE TITLE
what's the version of numpy? An error happens.

### ISSUE THREAD

**Issue by Zhang-ucas** [BUPT-GAMMA/OpenHGNN#199]
## ❓ Questions and Help
The error is as follow.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:

**Comment by lazishu2000** [comment]
The requirement of NumPy version is 1.20 or later.
