### ISSUE TITLE
关于DBLP数据集精度差的问题

### ISSUE THREAD

**Issue by WhatHowWhy1** [BUPT-GAMMA/OpenHGNN#201]
## ❓ Questions and Help

我想知道为什么我使用平台上面的DBLP数据集，用节点分类任务测试各个算法，精度却只有30多，这和其他论文DBLP精度差的很大。想请教这是什么原因

**Comment by Sylphid172** [comment]
Well,I'm not sure,but it seems that HGBn-DBLP considers the result of the valid set as the final result.At the same time dblp4magnn doesn't have this question.

**Comment by lazishu2000** [comment]
HGBn-DBLP数据集的测试需要上传模型到HGB官网进行，其目的是为了维护该榜单的公平性。
您可以在本地完成训练和验证，但后续的测试请移步HGB官网。
如果您想要在本地完成测试，请使用其他DBLP数据集例如dblp4magnn。
