### ISSUE TITLE
无法复现HGT在HGBn-ACM数据集上的结果

### ISSUE THREAD

**Issue by imaginistLi** [BUPT-GAMMA/OpenHGNN#210]
Readme中的结果：
![image](https://github.com/BUPT-GAMMA/OpenHGNN/assets/54342550/8608c0dc-7565-4df9-a6a3-d32f91e9fb70)

我的结果
![image](https://github.com/BUPT-GAMMA/OpenHGNN/assets/54342550/390a0e4b-1d6b-43fd-ad5f-884c2c0cd7ac)

**Comment by lazishu2000** [comment]
似乎是HGBn-ACM数据集本身出现问题，导致模型在该数据集上的表现都有所降低。
我们目前正在解决这个问题，如果你想测试HGT的模型性能，欢迎在其他数据集上先进行测试，HGBn-ACM的问题解决后会在这里评论回复。谢谢。

**Comment by lazishu2000** [comment]
你好，看起来mini-batch训练方式会对该数据集上的准确率产生一定影响。如果要复现readme中的模型效果请运行命令：
python main.py -m HGT -t node_classification -d HGBn-ACM -g 0 --use_best_config
在更新之后这会启动默认的full-batch训练，得到的结果大致与readme相符。
<img width="927" alt="截屏2024-03-05 16 55 35" src="https://github.com/BUPT-GAMMA/OpenHGNN/assets/106424231/92184286-e198-46d6-ab49-6381fab5d9bd">
