### ISSUE TITLE
HIN_LinkPrediction' object has no attribute 'get_idx'

### ISSUE THREAD

**Issue by xuptacm** [BUPT-GAMMA/OpenHGNN#57]
\OpenHGNN-main\openhgnn\tasks\link_prediction.py", line 32, in __init__
    self.train_hg, self.val_hg, self.test_hg = self.dataset.get_idx()
AttributeError: 'HIN_LinkPrediction' object has no attribute 'get_idx'

**Comment by xuptacm** [comment]
\Desktop\OpenHGNN-main> python main.py -m RGCN -d academic4HetGNN -t link_prediction -g -1 --use_best_config

**Comment by Theheavens** [comment]
Sorry for my late reply. And the dataset academic4HetGNN is only for HetGNN, you can try other datasets like HGBl-ACM，HGBl-DBLP, etc.
