### ISSUE TITLE
Error to run without Cuda

### ISSUE THREAD

**Issue by M-Somtirth** [BUPT-GAMMA/OpenHGNN#68]
File "C:\Users\XyZ\OpenHGNN\openhgnn\models\GTN_sparse.py", line 220, in forward
sum_g = dgl.adj_sum_graph(A, 'w_sum')
AttributeError: module 'dgl' has no attribute 'adj_sum_graph'

This Issue came-up while I ran the command= python main.py -m GTN -d imdb4GTN -t node_classification -g -1 --use_best_config

Can  someone say me where I  went  wrong?

**Comment by Theheavens** [comment]
Which version of DGL do you use?

**Comment by M-Somtirth** [comment]
DGL 0.6.1

**Comment by Theheavens** [comment]
It should be updated. The API `adj_sum_graph` is the new feature of version 0.7.
You could install the stable version or the nightly build version.
Refer to: https://www.dgl.ai/pages/start.html

**Comment by M-Somtirth** [comment]
Thanks its done!
