### ISSUE TITLE
关于HetGNN的evaluation

### ISSUE THREAD

**Issue by lixusign** [BUPT-GAMMA/OpenHGNN#69]
你好，我的异构图比较大，直接跑全图的eva过程会爆内存，完全和训练一样batch跑还要过随机游走过程。请问还有什么好的办法吗？

**Comment by Theheavens** [comment]
HetGNN应该是下游任务和训练分开的，训练收敛后获得节点的Embedding再去做evaluation，所以eva部分不会使用全图再去跑一遍。所以目前不是很理解您的问题？

**Comment by lixusign** [comment]
明白你的意思，不过图较大的情况下 batch 一次次的获取全图的emb耗时比较高，需要走随机游走。而全图训练则不需要走游走的过程（但是需要极大的内存）。不知道这里有什么思路可以改进优化下，加速下全图的emb获取，在较大图下

**Comment by lixusign** [comment]
比如我获取全部节点的emb, 用于后续任务。 但如果我mini-batch训练的话 ，要实时构建游走路径。然后走模型训练，需要很长的时间。而在全图训练过程中 并未走游走，但全图需要很大的内存。 因此想请教下是否有办法在构建全图emb中，无需做游走可以直接走模型的方法（batch训练）。

**Comment by lixusign** [comment]
具体来说 就是这一行了 https://github.com/BUPT-GAMMA/OpenHGNN/blob/1e9dfe33ca80be786cfec4f0920de1a4eec839d9/openhgnn/trainerflow/hetgnn_trainer.py#L123

**Comment by Theheavens** [comment]
我理解的意思是：目前train过程中可以使用mini-batch的方式，在eval过程中只有full-batch的方式。然而full batch不适用大图，对吗？
1、HetGNN的聚合方式决定了必须要Random Walk Restart, `het_graph`就是预先游走后形成的图。所以eval的时候，输入model的是游走后的图。
2、解决大图的eval的问题：可能还是需要像train一样，做mini-batch，分别获得节点的emb，最后拼起来。

**Comment by lixusign** [comment]
感谢，现在是这么做的，不过效率堪忧。只要切图就必须游走看来是？

**Comment by lixusign** [comment]
训练中是每个epoch 采一部分step做train。  而eva要恐怖的全部的step

**Comment by lixusign** [comment]
现在是8卡训练 + 单卡eva. 能想到的加速办法是把mini-batch游走的部分，在eva中，提前snapshot下来。

**Comment by Theheavens** [comment]
> 感谢，现在是这么做的，不过效率堪忧。只要切图就必须游走看来是？

不切图也需要游走，这是HetGNN模型决定的。

> The key idea of most graph neural networks (GNNs) is to aggregate feature information from a node’s direct (first-order) neighbors, such as GraphSAGE [7] or GAT [31].  However, directly applying these approaches to heterogeneous graphs may raise several issues:

HetGNN认为直接聚合的方式有局限性，所以提出RWR的方式来确定聚合哪些邻居。我个人认为这部分和其他部分是分离的，所以这个地方不用游走，直接使用原图也是可以的。如果能接受提高效率，降低性能，这是一种可以尝试的方法。

**Comment by lixusign** [comment]
好的，thx，暂时用8卡并行构建emb试试
