### ISSUE TITLE
关于HetGNN-emb有完全相同的情况

### ISSUE THREAD

**Issue by lixusign** [BUPT-GAMMA/OpenHGNN#70]
通过HetGNN跑提供的academic4HetGNN.zip 数据集。emb结果有完全相同的情况发生，原因未知。请问是否是符合预期的？

如下测试：

`import numpy as np

emb = np.load('emb50.npy')
list = emb[:,0]

for i in np.unique(list):
  idx = np.argwhere(list == i)
  r = idx.reshape(1, -1).squeeze(0)
  if len(r) > 1:
    print('index for {}:\n'.format(i), r)
    for j in r:
        print(emb[j])
`

**Comment by Theheavens** [comment]
1、emb[:,0]是否是只取每个emb的第0维度的值。
2、完全相同是指不同节点的值完全相同吗？可以给出一些运行结果吗？

**Comment by lixusign** [comment]
比如第145个epoch (我用的best_config).  [ 8185 10778 12513 17729]  节点的emb完全一样。比较困惑

**Comment by lixusign** [comment]
1、emb[:,0]是否是只取每个emb的第0维度的值。 
只用这个判断，然后取出对应的emb行再判断

2、完全相同是指不同节点的值完全相同吗？可以给出一些运行结果吗？
比如第145个epoch (我用的best_config). [ 8185 10778 12513 17729] 节点的emb完全一样。比较困惑

**Comment by lixusign** [comment]
复现方法：
python main.py -m HetGNN -d academic4HetGNN -t node_classification -g 0 --use_best_config --load_from_pretrained
在每个epoch保存emb
然后在181个epoch 看到如下节点id的emb完全一致

[    0  1077  3246  7980 12413 16949 24381 28624]

可用上面脚本片段测试

**Comment by lixusign** [comment]
请问有啥进展吗？还是我哪里理解的不对

**Comment by Theheavens** [comment]
1、我复现了实验，确认存在这个问题。
2、我查看了原文与代码。
最后的embedding是由content embedding与neighbor embedding组成；
查看了数据集本身，content embedding存在比较多的节点是由重复特征的，即content embedding重复；
要使得最后的结果节点完全一致，节点的neighbor embedding也要相同，即采样出的邻居相同，依据其采样算法，以及数据集特性，在某些节点邻居比较少时，其采样到的邻居会比较固定，造成其邻居一样的结果。
综上所述，我认为可能是该数据集可能会造成该问题。

**Comment by lixusign** [comment]
感谢回复，还有一点困惑的是在节点分类任务中，academic4HetGNN数据集训练到epoch=1 （use best config）即达到acc 95%以上, 后面在慢慢涨到97%  是否正常。

**Comment by Theheavens** [comment]
该数据集中的特征包涵deep walk获得的embedding，该embedding是依据图结构获得的，换言之不经过模型，输入特征至下游任务也能获得较好的性能。

**Comment by lixusign** [comment]
thx
