### ISSUE TITLE
关于HetGNN的emb顺序困惑

### ISSUE THREAD

**Issue by lixusign** [BUPT-GAMMA/OpenHGNN#72]
请教下 在 x = self.model(blocks[0], input_features) 中返回的x 是dict 。 他里面每种node_type 的emb 和blocks[0] 的入参的点的顺序如何对应？

我核对了以后 发现并不是 blocks[0].srcnodes[node_type].data[dgl.NID] 所代表的节点顺序。

**Comment by Theheavens** [comment]
输出特征是blocks[-1].dstnodes的节点顺序。
可以参考dgl的官方文档：https://docs.dgl.ai/en/latest/tutorials/large/L0_neighbor_sampling_overview.html#sphx-glr-tutorials-large-l0-neighbor-sampling-overview-py

**Comment by lixusign** [comment]
copy that
