### ISSUE TITLE
Model reference consultation

### ISSUE THREAD

**Issue by bisamlu** [BUPT-GAMMA/OpenHGNN#77]
Hi, do you have any references for homo_GNN model? The reference source of homo_GNN model was not found in the project

**Comment by Theheavens** [comment]
Hi, it is just homogeneous GNN like GCN\GAT\GraphSAGE with a type-specific linear transformation. We will give a simple description for homo_GNN/relation_HGNN/meta_HGNN. Before that, you could refer to [Space4HGNN: A Novel, Modularized and Reproducible Platform to Evaluate Heterogeneous Graph Neural Network](https://arxiv.org/abs/2202.09177).
