### ISSUE TITLE
Why not remove the test_idx from the train_graph?

### ISSUE THREAD

**Issue by SunShy1** [BUPT-GAMMA/OpenHGNN#91]
https://github.com/BUPT-GAMMA/OpenHGNN/blob/730f8445704aaacdd8fdba487169748fcb0d12a9/openhgnn/dataset/LinkPredictionDataset.py#L63

It seems that only 'val_index' is removed from 'train_graph', but 'test_index' is not removed.

**Comment by Theheavens** [comment]
You are right. The edges of `test_idx` should be removed. We fix the bug and thanks a lot!
