### ISSUE TITLE
Using my own dataset

### ISSUE THREAD

**Issue by Essie0715** [BUPT-GAMMA/OpenHGNN#94]
Hi
Is that possible that I use my own dataset？

**Comment by Zhanghyi** [comment]
This feature is in dev stage on branch dataset and it will be officially published soon.

**Comment by Theheavens** [comment]
For now, we just offer [a demo to support custom dataset](https://openhgnn.readthedocs.io/en/latest/install/usage.html#evaluate-a-new-dataset). Besides, we are developing an easier API to support custom dataset, like hongyi said.
