### ISSUE TITLE
Error when running fastGTN

### ISSUE THREAD

**Issue by huihuijiangqiang** [BUPT-GAMMA/OpenHGNN#99]
I get an error when I run fastGTN using:
`python main.py -m fastGTN -t node_classification -d acm4GTN -g 0 --use_best_config
`
The error is as follows：
`AttributeError: 'Config' object has no attribute 'identity'`

**Comment by Theheavens** [comment]
Thank you for reporting!
It has been fixed in https://github.com/BUPT-GAMMA/OpenHGNN/commit/760ac1ab5ffa9099ed9cbcbd5cde237c5cdb6765.
